source .env

FLAGS='-O0 -g -DDEBUG_MODE'
WARNINGS='-Winline -Wno-invalid-noreturn'
COMPILER=clang

OUTPUT_LOC="$OUTPUT_DIR/test.out"
BUILD_SPECIFIC_FILES='./gphrx/test/*.c'
TEST_INCLUDE_DIR='./gphrx/test'

mkdir -p $OUTPUT_DIR

$COMPILER -DDEBUG_MODE -DTEST_MODE $WARNINGS $FLAGS -I$INCLUDE_DIR -I$TEST_INCLUDE_DIR $FILES $BUILD_SPECIFIC_FILES -o $OUTPUT_LOC && $OUTPUT_LOC $@
