source .env
OUTPUT_LOC="$OUTPUT_DIR/test.out"
BUILD_SPECIFIC_FILES='./gphrx/test/*.c'

$COMPILER -DDEBUG_MODE -DTEST_MODE $WARNINGS $FLAGS -I$INCLUDE_DIR $FILES $BUILD_SPECIFIC_FILES -o $OUTPUT_LOC && $OUTPUT_LOC $@
